CC = cc
CFLAGS = -Wall -Wextra -Werror
RM = rm -rf
NAME = ft_printf.a

LIB_SRCS = ft_printf.c ft_printf_char.c ft_printf_digit.c\
				ft_printf_str.c ft_printf_unsigned.c

LIB_OBJS =  $(LIB_SRCS:.c=.o)

all: $(NAME)

$(NAME): $(LIB_OBJS)
	ar rc $(NAME) $(LIB_OBJS)

clean:
	$(RM) $(LIB_OBJS)
fclean: clean
	$(RM) $(NAME)
re: fclean all
